version: '3.8'

services:
  bot:
    build: .
    container_name: telegram-bot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - CHAT_ID=${CHAT_ID}
      - DATABASE_URL=postgres://trader:trader_pass@postgres:5432/trading?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "6127:6127"
    volumes:
      - .:/app
    command: ["./bot"]  # Запуск собранного бинарного файла

  postgres:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: trader
      POSTGRES_PASSWORD: trader_pass
      POSTGRES_DB: trading
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Добавляем инициализацию БД
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trader -d trading"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
